### ISSUE TITLE
Поправить имена переменных

### ISSUE THREAD

**Issue by pingvin1308** [ilyaik/Kupri4.SoftwareDevelop#4]
https://github.com/ilyaik/Kupri4.SoftwareDevelop/blob/279e3f7dc420bef89659a0b13ddd701437e7797c/Persistence/FileService.cs#L38

Старайся избегать любых сокращений в коде.
Времена, когда нужно было экономить на области памяти, где хранятся команды (код), уже прошли.
Сегодня опытные разработчики предпочитают разбираться с кодом, в котором все понятно описано.
А тут получается, что нужно найти где эта переменная инициализируется и только после этого ты поймешь что к чему :)
В целом сокращения в коде применяются, но это только в тех случаях, когда все выражение помещается в одну, две строчки. К примеру так делают при работате с лямбда выражениями.

вот небольшой код для примера.

```C#
var numbers = new[] { 1, 2, 4, 5, 6, 7 };
var oddNumbers = numbers.Where(x => x % 2 == 0).ToArray();
```

**Comment by ilyaik** [comment]
**Понял, уяснил!))**
Попробую аргументировать свои действия по наименованию: 
Придерживался следующей логики: 
Если переменная используется в небольшом фрагменте кода, то в принципе, я именую её одной буквой. 
это удобно, когда использую лямбда выражения.
переменная _p_ типа _Person_ используется в свиче далее и также в выводе на консоль.. 

ок, замечание мне понятно)
